# LLM-Optimized Starship Configuration
# Balances human readability with AI parseability

# Performance optimization
scan_timeout = 10
add_newline = false

# Color palette (for human readability)
palette = "catppuccin_macchiato"

# Simplified, structured format modules
[character]
success_symbol = '[→](bold green) '
error_symbol = '[✗](bold red) '

[directory]
truncation_length = 5
truncation_symbol = '…/'
format = '[$path]($style)[$read_only]($read_only_style) '

# Git status with text-based indicators (better for LLM parsing)
[git_branch]
symbol = 'git:'
format = '[$symbol$branch]($style) '
truncation_length = 20
ignore_branches = []

[git_status]
# Use text instead of emojis for better LLM parsing
conflicted = 'CONFLICT'
ahead = 'AHEAD'
behind = 'BEHIND'
diverged = 'DIVERGED'
up_to_date = 'CLEAN'
untracked = 'UNTRACKED'
stashed = 'STASHED'
modified = 'MODIFIED'
staged = 'STAGED'
renamed = 'RENAMED'
deleted = 'DELETED'
format = '([$all_status$ahead_behind]($style)) '

# Development context (structured output)
[python]
symbol = 'py:'
format = '[$symbol$pyenv_prefix$version]($style) '

[nodejs]
symbol = 'node:'
format = '[$symbol$version]($style) '

[rust]
symbol = 'rust:'
format = '[$symbol$version]($style) '

[java]
symbol = 'java:'
format = '[$symbol$version]($style) '

# Cloud context
[aws]
format = '[aws:$profile]($style) '
style = 'bold blue'

[gcloud]
format = '[gcp:$project]($style) '
style = 'bold blue'

# Container context
[docker_context]
format = '[docker:$context]($style) '
style = 'bold blue'

[kubernetes]
format = '[k8s:$context]($style) '
style = 'bold blue'
disabled = false

# System info (minimal for AI context)
[hostname]
ssh_only = false
format = '[@$hostname]($style) '
style = 'bold dimmed white'
disabled = false

[username]
format = '[$user]($style)'
style_user = 'bold white'
style_root = 'bold red'
show_always = true

# Time for session context
[time]
disabled = false
format = '[$time]($style) '
style = 'bold dimmed white'

# Performance indicators
[cmd_duration]
min_time = 2000
format = '[took:$duration]($style) '
style = 'bold yellow'

[memory_usage]
disabled = false
threshold = 75
format = '[mem:$ram]($style) '
style = 'bold dimmed green'

# Job control
[jobs]
symbol = 'jobs:'
format = '[$symbol$number]($style) '

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"